# [project]
# name = "dotfiles"
# version = "0.1.0"
# description = "Add your description here"
# readme = "README.md"
# requires-python = ">=3.14"
# dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    # ty is still a bit jank
    # "ty>=0.0.76",
]


[tool.ruff]
# package = false
line-length = 140

[tool.ruff.lint]
preview = true
select = [
    "E",
    "F",
    "W",
    "PTH",
    "TD",
    "RUF",
    "FURB",
    "Q",
    "PLE",
    "PLW",
    "PLR",
    "PLC",
    "SLF",
    "empty-docstring", # D419
]
ignore = [
    "missing-todo-author", # TD002
    "missing-todo-link",   # TD003
]
